sudo: false
language: node_js
node_js:
- 10.15.3
branches:
  only:
  - master
before_install:
- npm i -g npm
- npm config set loglevel warn
- echo "travis:rocks" > ~/.testingbot
script:
- karma start travis-karma.conf.js
addons:
  sauce_connect: true
env:
  global:
  - secure: BPkL/7vKsIt0YnusS6Y+vFEoralw3rPX1cPbmxkKCrMb2sIhp5HCOhZCewoOyV+mos0jBLIlsqp+aHPedBAsQppt9SLT9P1bMnaldTTq0HS8R6fCwNDSGBGXm3NTmXZPZ3f+sO4lepsaw3wUv0DjeDs4aqdGKh3ENkNA9LHq325h08WjkfbYRD1AuS6PoZH1vMBl3usCLNdkgFNlRFVa94GESRnff3E3vZRagrcdk4vP25aTIPBX00PzAsXzKhviEIsU4l/J3LnIdOHIsZakLsHeOr69HcoVEVSkV/X3FggJtwAmAf2sLobKO6L9n2sXPjlnmiZh8kGQmB/VO2YKwzJwUCdg2SleyP/4EF/rEJFbGjRWDz3hLaIsrjnODOTwbm9om6DTWXoW4AE8QXoLfE/CJmlo8VKSNyZPB/x0/QGl6fLiyzdKIUBYn/IXgdCQL/MDm6CnF2GXpOI0hs6CIHIDSfleYlm2WIl5FBL259x6Q3SBGRIJF7xZKj3M8kO9O+HicoHcIdArgC7QYi8z5jHagCmgXrn53m2+tT3/nrK7CaA9zxiRSgAdewNfBJLYbcb7nTXBnOtEeGkYybXNcC+DHhKxsd/JnZjOOXMEaGm1cqzTbBADNAqoadrfO8/xhttjegXj9j5aK7svjLaYwDXel7k/6UGgfAfI0RuHkV8=
  - secure: eQQpxnRpoGPPbxUY4G7JGuQtmITPyeThr3LeAq5REfHK/vTfDUmAlBw5vHWRDWuMl30dCHVtLuPnlC75xVwfPTosZG63oFe1FCpyYfyEsQNOkf5BKyVjsg2mND0ZBzEh+rqs1PUS2IQxLhJPMsKbZI7GvOmnQsyP7iqKDCEgB6PuxE3vzV40YDH14C/4I/RcnwTwqKDpGASZg4LnQSctm0rkY/TkTNGwGnVDeTivS+GVCrhwCbhHAaoWPJumbYQVjSdtrvYH++Wa/mma/Ah5xrW/J1pN6Ka1KPvlOHJTzTjYo4EIaXGdNukrdyvUz6kQQPoFksG8sYEQBgXzIhcUtZSzb8Dfb0eQiwt+YYlKVkVqYI/nLZlOTHnmTa+D0Iurx5WLovtOOaMwuazC4lNaQ2QXOgNKuokUsAAD27TkjfR5HtLgEfxHDCHYxpSz8WqJwej9OSVbeJe7UYkXYRKkii51MG4wtMmjNmW1e/W0HS0n95145fi+vD4Mdw0otoxIBIEOUR4/ghu9FFcHvFktvmZIAAvDH3PuU1OpG8WX4uvqQsqWO+BVG77Y6kDM3d3JelR7sWRGNqQJ5zWLjDkd30Qmx0IIruk4zi+6rh0eNteToCjQuGYTG7vkv4XsRLcfLvbfArK6I+kaDEI3xv98pZSgJerrCoaXMRUdlkf0AlA=
  - secure: 21DPYbPTPaQr2jFcIaGLKQS6emxetJp4q+sJ/hnGfi4eCG9RZZ0FCWKlhDfh8e/1E3Yp63eScqGfEenU6LXVLDpwKth6/V2nlWsXBH5ZOqB/HIva8wBKeqvi4f7D2/apc+uQeNUeVA/at7nlGlBd4qqiM4hQMzW5CW6pnQuP3438ZaWeKASbrb1xdw/6c3vZ3mKjeL2HUUVhFQuU2TX5ROTeoD7r3rokt6AQR0S6S9OrzsHptuXTkXmBIlng9jlRzIsx696D67IJCduecTbFCZTL8dvVuvq+iNne9u01kYBPujBS2znAZcpSQNK3qlHYW6E631EUU2dWTuLOO0itTN1vZWQ7kGXg2svli02odgkQkPyWRlsRDff0ad+2ubXJvy3i/RJujtB31+1BrZp2BVWMoTytFd5LVElG8hcqro4VyfPMhgpp7iSIfUrnlf1QAzgc1qKCINvXQU1Io/+xRDTSOTkK0MXeMA6D0BgN+UHm4g4MGwJIK++/wuF0P+iCwNW2IXvobiC+4uPgtXNILWMEt4MIEydg4oSMMo00S5ccro+EHQkNaQi63bTU7rUi/6kOLOkcB+W0AjgEo3nrOnpSup3OD+AAVN8Nk0VM7oBca8hCgXDIxsT4005GKnEqKtgF9RpwJnwTufcgPRPpL1YbuS65WWmS27Ll1xG2j0c=
